# Configuration for "other dataset" section, see type `StorageDatasetEntry` for details.
# The value for the dataset key should match the file name of the dataset in the ai4e dataset repo.
ghe:
  title: Global Hydro Estimator
  category: Climate/Weather
  short_description: Global precipitation estimates
  infoUrl: http://aka.ms/ai4edata-ghe
  thumbnailUrl: RE4ucH7.jpg
  keywords: [NOAA, Global, Precipitation]

goes-fdc:
  title: GOES Fire Detection and Characterization (FDC)
  category: Climate/Weather
  short_description: Maps of fires, including radiative power, temperature, size, and classification
  infoUrl: https://microsoft.github.io/AIforEarthDataSets/data/goes-fdc.html
  thumbnailUrl: goes-fdc-thumbnail.png
  keywords: [GOES, NOAA, Fire]

goes-lst:
  title: GOES Land Surface Temperature (LST)
  category: Temperature
  short_description: Land Surface Temperature (LST) estimation
  infoUrl: https://microsoft.github.io/AIforEarthDataSets/data/goes-lst.html
  thumbnailUrl: goes-lst-thumbnail.png
  keywords: [GOES, NOAA, Temperature]

goes-rrqpe:
  title: GOES Rainfall Rate and Quantitative Precipitation Estimation (RRQPE)
  category: Weather
  short_description: Maps of expected rainfall rate and precipitation
  infoUrl: https://microsoft.github.io/AIforEarthDataSets/data/goes-rrqpe.html
  thumbnailUrl: goes-rrqpe-thumbnail.png
  keywords: [GOES, NOAA, Rainfall, Precipitation]

goes-sst:
  title: GOES Sea Surface Temperature (SST)
  category: Temperature
  short_description: Sea Surface Temperature (SST) estimate.
  infoUrl: https://microsoft.github.io/AIforEarthDataSets/data/goes-sst.html
  thumbnailUrl: goes-sst-thumbnail.png
  keywords: [GOES, NOAA, Ocean, Temperature]

doe-wave:
  title: High Resolution Ocean Surface Wave Hindcast
  category: Water
  short_description:
    Long-term wave hindcast data for the U.S. Exclusive Economic Zone (EEZ)
  infoUrl: https://aka.ms/ai4edata-doe-wave
  thumbnailUrl: wave-hindcast_small.jpg
  keywords: [Wave, hindcast, United States]

hls:
  title: Harmonized Landsat Sentinel-2
  category: Imagery
  short_description: 30m-resolution satellite imagery for North America
  infoUrl: http://aka.ms/ai4edata-hls
  thumbnailUrl: RE3OM3E.jpg
  keywords: [Landsat, Sentinel, Satellite, Imagery, North America]

lila-bc:
  title: LILA BC
  category: Biodiversity
  short_description: Labeled images related to wildlife conservation
  infoUrl: http://lila.science/
  thumbnailUrl: RE3BWhq.jpg
  keywords: [LILA, Labels, Wildlife, Biodiversity]

nlcd:
  title: National Land Cover Database
  category: Land use/Land cover
  short_description: US-wide data on land cover and land cover change
  infoUrl: https://aka.ms/ai4edata-nlcd
  thumbnailUrl: RWz0Zh.jpg
  keywords: [United States, NLCD, Land Cover]

nsrdb:
  title: National Solar Radiation Database
  category: Solar
  short_description:
    Half-hourly measurements of incident solar radiation from 1998-present
  infoUrl: https://aka.ms/ai4edata-nsrdb
  thumbnailUrl: solar_radiation_small.jpg
  keywords: [United States, Solar, Radiation]

noaa-cfs:
  title: NOAA Climate Forecast System
  category: Climate/Weather
  short_description: Global weather forecasts at approximately 56km resolution
  infoUrl: https://aka.ms/ai4edata-cfs
  thumbnailUrl: global_weather_2.jpg
  keywords: [Global, NOAA, Climate, Forecast]

noaa-gefs:
  title: NOAA Global Ensemble Forecast System (GEFS)
  category: Climate/Weather
  short_description: Ensembled global weather forecasts
  infoUrl: https://aka.ms/ai4edata-gefs
  thumbnailUrl: global_weather_3.jpg
  keywords: [Global, NOAA, Weather, Forecast]

noaa-gfs:
  title: NOAA Global Forecast System
  category: Climate/Weather
  short_description: 15-day US hourly weather forecast data
  infoUrl: https://aka.ms/ai4edata-gfs
  thumbnailUrl: RE4rvnx.jpg
  alt: Earth viewed from space station with a satellite
  keywords: [Global, NOAA, Weather, Temperature, Precipitation]

gfs-warm-start:
  title: NOAA GFS Warm Start Conditions
  category: Climate/Weather
  short_description:
    Six-hourly initial conditions for the NOAA Global Forecast System
  infoUrl: https://aka.ms/ai4edata-gfs-warm-start
  thumbnailUrl: RE4MHyn.jpg
  keywords: [Global, NOAA, Weather, Temperature, Precipitation]

noaa-hrrr:
  title: NOAA High-Resolution Rapid Refresh (HRRR)
  category: Climate/Weather
  short_description: Weather forecasts for North America at 3km resolution
  infoUrl: https://aka.ms/ai4edata-hrrr
  thumbnailUrl: hrrr_small.jpg
  keywords: [North America, NOAA, Weather, Forecast]

noaa-isd:
  title: NOAA Integrated Surface Data
  category: Climate/Weather
  short_description: Worldwide hourly weather history data
  infoUrl: https://aka.ms/ai4edata-isd
  thumbnailUrl: RE4rsOQ.jpg
  keywords: [Global, NOAA, Weather, Temperature, Precipitation]

noaa-nwm:
  title: NOAA National Water Model
  category: Water
  short_description: Streamflow forecasts for the contiguous US, Hawaii and Puerto Rico
  infoUrl: https://microsoft.github.io/AIforEarthDataSets/data/noaa-nwm.html
  thumbnailUrl: noaa-nwm-thumbnail.png

  keywords: [Global, NOAA, Streamflow, Hydrology, Water, NWM]

noaa-rap:
  title: NOAA Rapid Refresh (RAP)
  category: Climate/Weather
  short_description: Weather forecasts for North America at 13km resolution
  infoUrl: https://aka.ms/ai4edata-rap
  thumbnailUrl: thunder_storm.jpg
  keywords: [North America, NOAA, Weather]

ooi-camhd:
  title: Ocean Observatories Initiative CAMHD
  category: Biodiversity
  short_description: High-resolution video from the floor of the Pacific Ocean
  infoUrl: https://aka.ms/ai4edata-ooi-camhd
  thumbnailUrl: RE4KiKZ.jpg
  keywords: [OOI, Video, Ocean, Pacific]

sentinel-1-slc:
  title: Sentinel-1 SLC
  category: SAR
  short_description: Global synthetic aperture radar data for the last 90 days
  infoUrl: https://aka.ms/ai4edata-sentinel-1-slc
  thumbnailUrl: sentinel-1-sat.jpg
  keywords: [Global, Sentinel, Satellite, ESA, SAR]

uk-met-20crds:
  title: UK Met Office CSSP China 20CRDS
  category: Climate/Weather
  short_description: Historical climate data for China, from 1851-2010
  infoUrl: https://aka.ms/ai4edata-uk-met-20crds
  thumbnailUrl: cssp-china.jpg
  keywords: [Met Office, China, Climate, Historical]

uk-met-covid-19:
  title: UK Met Office Global Weather Data for COVID-19 Analysis
  category: Climate/Weather
  short_description:
    Data to explore relationships between COVID-19 and environmental factors
  infoUrl: https://aka.ms/ai4edata-metofficecovid19
  thumbnailUrl: covid-dot-map.jpg
  keywords: [Met Office, Global, COVID-19, Weather]

umcm-hurricanes:
  title: UMCM Hurricanes
  category: Climate/Weather
  short_description:
    Modeled wind, wave, and current data for Hurricanes Ike and Sandy
  infoUrl: https://aka.ms/ai4edata-umcm-hurricanes
  thumbnailUrl: hurricane_small.jpg
  keywords: [UMCM, Hurricane, Wind, Wave, Current, Ocean]
