#!/bin/bash

set -e

function usage() {
    echo -n "Usage: $(basename "$0")
Runs frontend tests and linter
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        docker compose \
            -f docker-compose.yml \
            run --rm --no-deps app \
            npm run build

        docker compose \
            -f docker-compose.yml \
            run --rm --no-deps app \
            cp staticwebapp.config.json build/
    fi
fi
