#!/bin/bash

set -e

function usage() {
    echo -n "Usage: $(basename "$0")
Remove files build from various ETL processes
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        docker compose run --rm --entrypoint ./scripts/clean etl
    fi
fi
