#!/bin/bash

set -e

function usage() {
    echo -n "Usage: $(basename "$0")
Run formatters on python and JS files
"
}

function run() {

    docker compose run --rm --no-deps api black --check .
    docker compose run --rm --no-deps app npm run format-fix
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    case "${1}" in
        --help)
            usage
            ;;
        *)
            run ;;
    esac
fi
