#!/bin/bash

set -e

function usage() {
    echo -n "Usage: $(basename "$0")
Serve a mock STAC v1 endpoint for static collections
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        docker-compose up mockstac && docker-compose rm -fs
    fi
fi
