#!/bin/bash

set -e

function usage() {
    echo -n "Usage: $(basename "$0")
Run webpack dev server with hot reloading for development
    --full: run dev server plus function app emulator
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    elif [[ "${1:-}" == "--full" ]]; then
        swa start http://localhost:3000 --run "yarn start" --api-location ./api
    else
        yarn start
    fi
fi
