#!/bin/bash

set -e

function usage() {
    echo -n "Usage: $(basename "$0")
Runs frontend tests and linter
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        npm lint
        npm test
    fi
fi
