#!/bin/bash

set -e

function usage() {
    echo -n "Usage: $(basename "$0")
Runs frontend tests and linter
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        docker-compose \
            run --rm --no-deps app \
            npm run lint

        docker-compose \
            run --rm --no-deps app \
            npm run format

        docker-compose \
            run --rm --no-deps \
            -e CI="${CI}" \
            app \
            npm run test
    fi
fi
