#!/bin/bash

set -e

function usage() {
    echo -n "Usage: $(basename "$0")
Update and install project dependencies and run ETL jobs.

Options:
--devdocs: Build documentation site using a local server for external notebooks
"
}

function run() {

    # Install JS dependencies on host
    yarn

    # Ensure container images are current
    docker-compose build

    # Run etl to build documentation and external notebook/md files
    docker-compose run --rm --no-deps etl "${params[@]}"
}

params=()
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    case "${1}" in
        --help)
            usage
            ;;
        --devdocs)
            params+=("--devdocs")
            run
            ;;
        *)
            run ;;
    esac
fi