#!/bin/bash

DOCS_OUTPUT=_docs_output

# TODO: Add a clean flag:
# if [ -d "$DOCS_OUTPUT" ]; then rm -rf "${DOCS_OUTPUT}"; fi

# Build the docs directory with the JSON output type.
sphinx-build -b json ../docs "${DOCS_OUTPUT}" -v

# Copy over all of the *.fjson files to our src/docs directory,
# preserving the directory structure.
pushd $DOCS_OUTPUT
find . -name '*.fjson' -exec cp --parents \{\} ../../src/docs \;
popd

# Not currently using these files, remove them so they aren't imported
# into the app.
rm ../src/docs/genindex.fjson
rm ../src/docs/search.fjson

# Rename all fjson files to json.
# See: https://mywiki.wooledge.org/BashFAQ/030
find ../src/docs -type f -name '*.fjson' -print0 | while IFS= read -r -d '' f; do
  mv -- "$f" "${f%.fjson}.json"
done

# We also need the contents of the _images directory moved to the static build
# directory. Since these aren't imported into the app, they are not put in the
# src tree.
pushd $DOCS_OUTPUT
cp --parents _images/*.png ../../public
popd
