# file_url:   Absolute URL of notebook, or if relative, assumed to be a descendent of
#             https://github.com/microsoft/PlanetaryComputerExamples/raw/main/.
# image_urls: Optional list of URLs for associated image files. If relative, assumed to be a descendant
#             of img directory.
#
# Full example:
# - file_url: tutorials/landcover.ipynb
#   image_urls:
#     - tutorials/images/change.png
#     - tutorials/images/another.png
---
- file_url: tutorials/cloudless-mosaic-sentinel2.ipynb
- file_url: tutorials/customizable-rtc-sentinel1.ipynb
- file_url: tutorials/landcover.ipynb
- file_url: tutorials/hurricane-florence-animation.ipynb
  image_urls:
    - tutorials/images/change.png
- file_url: quickstarts/scale-with-dask.ipynb
  image_urls:
    - quickstarts/images/cluster-options.png
    - quickstarts/images/dashboard-hub.png
    - quickstarts/images/dashboard-tab.png
- file_url: quickstarts/reading-stac.ipynb
- file_url: quickstarts/reading-stac-r.ipynb
- file_url: quickstarts/stac-geoparquet.ipynb
- file_url: quickstarts/using-radiant-mlhub-api.ipynb
- file_url: quickstarts/reading-tabular-data.ipynb
- file_url: quickstarts/reading-zarr-data.ipynb
- file_url: quickstarts/storage.ipynb
