name: Cypress Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_ROOT: https://planetarycomputer-staging.microsoft.com
      CHOKIDAR_USEPOLLING: 1
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install-command: npm install
          start: npm start
          wait-on: http://localhost:3000
          wait-on-timeout: 95
          browser: chrome
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
