name: Cypress Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_ROOT: https://planetarycomputer-staging.microsoft.com
      CHOKIDAR_USEPOLLING: 1
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@d79d2d530a66e641eb4a5f227e13bc985c60b964 # v4.2.2
        with:
          install-command: npm install
          start: npm start
          wait-on: http://localhost:3000
          wait-on-timeout: 95
          browser: chrome
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
